version : '3'

services:

     application : 
         image :  application
         ports : 
          - '8080:8080'

      applicationdb : 
          image : applicationdb
          ports : 
          - '9099:3306'