version: '3'

services:
   zookeeper:
      image: 'confluentinc/cp-zookeeper:latest'
      hostname: 'zookeeper'
      ports:
         - '2181:2181'
      environment:
         ZOOKEEPER_CLIENT_PORT : 2181
         ZOOKEEPER_TICK_TIME : 2000


   kafka:
      image: 'confluentinc/cp-kafka:latest'
      hostname: 'localhost'
      ports:
        - '9092:9092'
      #hostname: 'kafka'
      environment:
         KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
         KAFKA_BROKER_ID : 1
         KAFKA_ADVERTISED_LISTENERS : 'PLAINTEXT://localhost:9092'

        #- KAFKA_ADVERTISED_HOST_NAME=kafka
        #- KAFKA_ADVERTISED_PORT=9092 
        #KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        #- KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
        #- KAFKA_CFG_LISTENERS=PLAINTEXT://localhost:9092
        #- KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      depends_on:
        - zookeeper
   #kafkaclient:
    #image: kafkaclient
    #ports:
       #- "9090:9090"
    #depends_on:
       #- kafka
    
