version: "3"
services:
  application:
    image: application
    ports:
      - "8080:8080"
    networks:
      - application-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/ListOfDevices?autoReconnect=true&useSSL=false
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - application-network
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ListOfDevices
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root 

networks:
  application-network:
